modules:
  - name: "service system 服务系统"
    code: "000"
    prefix: "Service"
    file: "service.yaml"
#  - name: "请求错误 request error"
#    code: "001"
#    prefix: "Request"
#    file_name: "request.yaml"
#  - name: "通用数据错误 common data error"
#    code: "100"
#    prefix: "Data"
#    file_name: "data"