specific_errors:
  - suffix: "InternalError"
    code: "000"
    desc: "Internal error 通用服务内部错误"
  - suffix: "Unavailable"
    code: "001"
    desc: "Service unavailable 服务不可用"
  - suffix: "Timeout"
    code: "002"
    desc: "Service timeout 服务自身任务超时"
  - suffix: "Busy"
    code: "003"
    desc: "Service is busy 服务器繁忙"
  - suffix: "Degradation"
    code: "004"
    desc: "Service degradation 服务降级停用"
  - suffix: "Obsolete"
    code: "005"
    desc: "Service is obsolete 服务已过期"
  - suffix: "DependencyUnavailable"
    code: "006"
    desc: "Service dependency unavailable 服务依赖不可达"