specific_errors:
  - name: "InternalError"
    code: "000"
    description: "通用服务内部错误 internal error"
  - name: "Unavailable"
    code: "001"
    description: "服务不可用 service unavailable"
  - name: "Timeout"
    code: "002"
    description: "服务自身任务超时 service timeout"
  - name: "Busy"
    code: "003"
    description: "服务器繁忙 service is busy"
  - name: "Degradation"
    code: "004"
    description: "服务降级停用 service degradation"
  - name: "Obsolete"
    code: "005"
    description: "服务已过期 service is obsolete"
  - name: "DependencyUnavailable"
    code: "006"
    description: "服务依赖不可达 service dependency unavailable"